
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                   Environment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# https://wiki.hypr.land/Configuring/Environment-variables/

# Cursor theme (Catppuccin Mocha Mauve)
env = HYPRCURSOR_THEME,catppuccin-mocha-mauve-cursors
env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,catppuccin-mocha-mauve-cursors
env = XCURSOR_SIZE,24
env = QT_CURSOR_SIZE,24

# Qt theming (Kvantum)
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_STYLE_OVERRIDE,kvantum

# NVIDIA Configuration
env = LIBVA_DRIVER_NAME,nvidia
env = NVD_BACKEND,direct
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia